/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Clases.Carrera;
import Clases.Reporte1;
import Clases.Reporte4;

import conexion.Reporte1Conexion;
import conexion.ParticipanteConexion;
import conexion.ReportesConexion;
import control.control;
import javax.swing.table.TableColumnModel;


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Time;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RojeruSan
 */
public class Reporte6_vista extends javax.swing.JFrame {

    
    control con = new control();
    
    ArrayList<Reporte4> lista = new ArrayList<Reporte4>();
    
    ReportesConexion reporte_conexion = new ReportesConexion();
    
    String fabricante;
    
    int contador = 0;
    int id_donde_termina = 0;
    int id_anterior = 0;
    int numero_evento_viejo = 0;
   
    
  public Reporte6_vista() {
        initComponents();
        
        con.iniciaVentana(this);
       
        this.setLocationRelativeTo(this);
            this.setSize(1800,1800);
        btnsiguiente1.setVisible(false);
        btnanterior.setVisible(false);
         
        con.llenarComboFabricantes(combo_fabricante);
        
       
          
    }

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnCerrar = new javax.swing.JButton();
        etiquetaTiempo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_nombre_equipo = new javax.swing.JLabel();
        combo_modelo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_nombre_conductor = new javax.swing.JLabel();
        txt_apellido = new javax.swing.JLabel();
        txt_nacionalidad_conductor = new javax.swing.JLabel();
        etiquetaTiempo2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_fabricante = new javax.swing.JLabel();
        txt_motor = new javax.swing.JLabel();
        txt_categoria = new javax.swing.JLabel();
        nohay = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_nombre_conductor1 = new javax.swing.JLabel();
        txt_apellido1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txt_nacionalidad_conductor1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txt_nombre_conductor2 = new javax.swing.JLabel();
        txt_apellido2 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txt_nacionalidad_conductor2 = new javax.swing.JLabel();
        etiquetaTiempo3 = new javax.swing.JLabel();
        btnanterior = new javax.swing.JButton();
        btnsiguiente1 = new javax.swing.JButton();
        combo_fabricante = new javax.swing.JComboBox<>();
        txt_modelo = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_tipo = new javax.swing.JLabel();
        etiquetaTiempo4 = new javax.swing.JLabel();
        etiquetaTiempo5 = new javax.swing.JLabel();
        txtnumero_equipo = new javax.swing.JLabel();
        fabricante_type = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCerrar.setBackground(new java.awt.Color(0, 153, 204));
        btnCerrar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setText("X");
        btnCerrar.setBorder(null);
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrar.setOpaque(true);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 30, 43, 45));

        etiquetaTiempo.setFont(new java.awt.Font("Lucida Sans", 0, 36)); // NOI18N
        etiquetaTiempo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaTiempo.setText("Datos del Automovil");
        jPanel1.add(etiquetaTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 280, 390, 90));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Nombre:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 120, 40));

        txt_nombre_equipo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txt_nombre_equipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 440, 40));

        combo_modelo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        combo_modelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_modeloActionPerformed(evt);
            }
        });
        jPanel1.add(combo_modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 110, 290, 40));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 140, 120, 50));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Numero de Equipo:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 210, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Posición:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 110, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("Nombres:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 640, 110, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("Apellidos:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 680, 120, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Nacionalidad:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 720, 160, 40));

        txt_nombre_conductor.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txt_nombre_conductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 640, 310, 40));

        txt_apellido.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txt_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 680, 330, 40));

        txt_nacionalidad_conductor.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txt_nacionalidad_conductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 720, 280, 40));

        etiquetaTiempo2.setFont(new java.awt.Font("Lucida Sans", 0, 36)); // NOI18N
        etiquetaTiempo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaTiempo2.setText("Datos de los Conductores");
        jPanel1.add(etiquetaTiempo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 540, 450, 90));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("Fabricante:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 360, 130, 40));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setText("Motor:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 360, 90, 40));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setText("Categoría:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 400, 130, 40));

        txt_fabricante.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txt_fabricante, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 360, 330, 40));

        txt_motor.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txt_motor, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 360, 300, 40));

        txt_categoria.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txt_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 400, 250, 40));

        nohay.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nohay.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(nohay, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, 380, 40));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel15.setText("Nombres:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 640, 110, 40));

        txt_nombre_conductor1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txt_nombre_conductor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 640, 290, 40));

        txt_apellido1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txt_apellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 680, 310, 40));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel16.setText("Apellidos:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 680, 120, 40));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel17.setText("Nacionalidad:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 720, 160, 40));

        txt_nacionalidad_conductor1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txt_nacionalidad_conductor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 720, 270, 40));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel18.setText("Nombres:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 640, 110, 40));

        txt_nombre_conductor2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txt_nombre_conductor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 640, 410, 40));

        txt_apellido2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txt_apellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 680, 400, 40));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel19.setText("Apellidos:");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 680, 120, 40));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel20.setText("Nacionalidad:");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 720, 160, 40));

        txt_nacionalidad_conductor2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txt_nacionalidad_conductor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 720, 280, 40));

        etiquetaTiempo3.setFont(new java.awt.Font("Lucida Sans", 0, 36)); // NOI18N
        etiquetaTiempo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaTiempo3.setText("Modelo");
        jPanel1.add(etiquetaTiempo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 30, 320, 90));

        btnanterior.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnanterior.setText("Anterior");
        btnanterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnanteriorActionPerformed(evt);
            }
        });
        jPanel1.add(btnanterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 200, 170, 50));

        btnsiguiente1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnsiguiente1.setText("Siguiente");
        btnsiguiente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsiguiente1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnsiguiente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 200, 170, 50));

        combo_fabricante.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        combo_fabricante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                combo_fabricanteMouseClicked(evt);
            }
        });
        combo_fabricante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_fabricanteActionPerformed(evt);
            }
        });
        jPanel1.add(combo_fabricante, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, 280, 40));

        txt_modelo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txt_modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 400, 360, 40));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel13.setText("Modelo:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 400, 90, 40));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setText("Tipo:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 440, 60, 40));

        txt_tipo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txt_tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 440, 330, 40));

        etiquetaTiempo4.setFont(new java.awt.Font("Lucida Sans", 0, 36)); // NOI18N
        etiquetaTiempo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaTiempo4.setText("Datos del Equipo");
        jPanel1.add(etiquetaTiempo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 320, 90));

        etiquetaTiempo5.setFont(new java.awt.Font("Lucida Sans", 0, 36)); // NOI18N
        etiquetaTiempo5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaTiempo5.setText("Fabricante");
        jPanel1.add(etiquetaTiempo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 200, 90));

        txtnumero_equipo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txtnumero_equipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 100, 40));

        fabricante_type.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fabricante_type.setForeground(new java.awt.Color(204, 204, 204));
        fabricante_type.setText("Buscar por Nombre");
        fabricante_type.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fabricante_typeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fabricante_typeMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fabricante_typeMousePressed(evt);
            }
        });
        fabricante_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fabricante_typeActionPerformed(evt);
            }
        });
        fabricante_type.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fabricante_typeKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fabricante_typeKeyTyped(evt);
            }
        });
        jPanel1.add(fabricante_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 40, 280, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-130, 0, 1570, 910));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        Principal ventana = new  Principal();
                   con.activaVentana(ventana, this);  
                   
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try{
            nohay.setText("");
     
        
       String fabricante = combo_fabricante.getSelectedItem().toString();
        String modelo = combo_modelo.getSelectedItem().toString();
       
            
        this.lista = reporte_conexion.reporte6(fabricante,modelo);
        
        subir();
        
        if(this.lista.size() == 0)
        nohay.setText("No hay Registros de esta Busqueda");
        else if (this.lista.size() > 0){
            btnsiguiente1.setVisible(true);
        }
        }catch(Exception e){
            nohay.setText("No hay Registros de esta Busqueda");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void combo_modeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_modeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_modeloActionPerformed

    private void btnanteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnanteriorActionPerformed
        this.contador --;
        btnsiguiente1.setVisible(true);
        try{
            anterior();
        }catch(Exception e){
            btnanterior.setVisible(false);
        }
    }//GEN-LAST:event_btnanteriorActionPerformed

    private void btnsiguiente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsiguiente1ActionPerformed
        this.contador ++;
        btnanterior.setVisible(true);
        try{
            siguiente();
            
        }catch(Exception e){
            btnsiguiente1.setVisible(false);
        }
    }//GEN-LAST:event_btnsiguiente1ActionPerformed

    private void combo_fabricanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_fabricanteActionPerformed
         combo_modelo.removeAllItems();
        this.fabricante = combo_fabricante.getSelectedItem().toString();
       
        if(!this.fabricante.isEmpty())
       con.llenarComboModelos(this.fabricante,combo_modelo);
    }//GEN-LAST:event_combo_fabricanteActionPerformed

    private void combo_fabricanteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combo_fabricanteMouseClicked
     
    }//GEN-LAST:event_combo_fabricanteMouseClicked

    private void fabricante_typeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fabricante_typeKeyTyped
        System.out.println("marque una letra");
        
        String fabricante = fabricante_type.getText();
        
        con.llenarComboFabricantes(fabricante,combo_fabricante);
        
    }//GEN-LAST:event_fabricante_typeKeyTyped

    private void fabricante_typeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fabricante_typeKeyPressed
       
        
    }//GEN-LAST:event_fabricante_typeKeyPressed

    private void fabricante_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fabricante_typeActionPerformed
       
    }//GEN-LAST:event_fabricante_typeActionPerformed

    private void fabricante_typeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fabricante_typeMouseClicked
         
    }//GEN-LAST:event_fabricante_typeMouseClicked

    private void fabricante_typeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fabricante_typeMouseEntered
         
    }//GEN-LAST:event_fabricante_typeMouseEntered

    private void fabricante_typeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fabricante_typeMousePressed
       fabricante_type.setText("");
    }//GEN-LAST:event_fabricante_typeMousePressed

    
    public void subir(){
        
        
       try{
        int marcador = this.id_donde_termina;
        int contador = 0;
        int i = 0;
        
       
                
                if(this.lista.get(0).getCantidad_pilotos() == 3){
                  mostrar(0,0);
                  mostrar(0+1,1);
                  mostrar(0+2,2);
                  this.id_donde_termina = 3;
                  }else{
                     mostrar(0,0);
                  mostrar(0+1,1);
                  mostrar(0+2,2);
                  this.id_donde_termina = 3;
                }
                
                if(this.lista.size() > 3){
                     btnsiguiente1.setVisible(true);
                }else{
                    btnsiguiente1.setVisible(false);
                }
       }catch(Exception e){
           System.out.println("llego al final");
       }
       }
    
    public void siguiente(){
        
        try{
        
           
        int cantidad_pilotos = 0;
        int contador = 0;
        int i = this.id_donde_termina;
        int o=0;
       
        
       if(this.lista.size() != i){
              if(this.lista.get(i).getCantidad_pilotos() == 3){
                  this.id_anterior = i-1;
                  mostrar(i,0);
                  mostrar(i+1,1);
                  mostrar(i+2,2);
                  
                  i= i+3;
                  this.id_donde_termina = i;
              
            } 
              
       }
          
       if(this.lista.size() == i){
           btnsiguiente1.setVisible(false);
             System.out.println("llego al final en siguiente");
       }
       
       
        }catch(Exception e){
            
            //ocultamos el boton siguiente ya que llego al final
             btnsiguiente1.setVisible(false);
             System.out.println("error en siguiente");
         }
       
       }
    
    
    public void anterior(){
        
        try{
        
           
        int cantidad_pilotos = 0;
        int contador = 0;
        int i = this.id_anterior;
        int o=0;
       
           
            
       if(this.id_anterior != -1){
              if(this.lista.get(i).getCantidad_pilotos() == 3){
                  mostrar(i-2,0);
                  mostrar(i-1,1);
                  mostrar(i,2);
                  this.id_anterior = i - 3;
                 
                  this.id_donde_termina = i+1;
              
            } 
              
       }
       
       if(this.id_anterior == -1){
           btnanterior.setVisible(false);
             System.out.println("llego al final en anterior");
       }
       
       
        }catch(Exception e){
            
            //ocultamos el boton siguiente ya que llego al final
             btnanterior.setVisible(false);
             System.out.println("error en anterior");
         }
       
       }
 
    
    public void mostrar(int contador,int piloto){
       // System.out.println("imprimir   contador "+contador+"   piloto  "+piloto );
        if(piloto == 0){
        txt_nombre_equipo.setText(lista.get(contador).getNombre_equipo());
        txtnumero_equipo.setText(Integer.toString(lista.get(contador).getNumero_equipo()));
       // txt_nacionalidad_equipo.setText(lista.get(contador).getNacionalidad_equipo());
        
       /* txt_puesto_carrera.setText(Integer.toString(lista.get(contador).getPosicioncarrera()));
        txt_numero_vuelta.setText(Integer.toString(lista.get(contador).getVueltascarrera()));
        txt_km.setText(Double.toString(lista.get(contador).getKmcarrera()));
        txt_mejor_vuelta.setText(lista.get(contador).getVuelta_rapida_carrera());
        txt_velocidad_media.setText(Double.toString(lista.get(contador).getVelocidad_media()));
        
        DecimalFormat df = new DecimalFormat("#0.00");
             
        txt_diferencia.setText(df.format(lista.get(contador).getDiferencia()));*/
       
        txt_fabricante.setText(lista.get(contador).getFabricante());
        txt_modelo.setText(lista.get(contador).getModelo());
        txt_motor.setText(lista.get(contador).getCaracteristicas_vehiculo());
        txt_categoria.setText(lista.get(contador).getCategoria_vehiculo());
        txt_tipo.setText(lista.get(contador).getTipo_vehiculo());
        
          txt_nombre_conductor.setText(lista.get(contador).getNombre_piloto());
        
       txt_apellido.setText(lista.get(contador).getApellido());
        
        
        txt_nacionalidad_conductor.setText(lista.get(contador).getNacionalidad());
        } else if ((piloto == 1) || (piloto == -1)){
             
                   txt_nombre_conductor1.setText(lista.get(contador).getNombre_piloto());

                 txt_apellido1.setText(lista.get(contador).getApellido());
                
                txt_nacionalidad_conductor1.setText(lista.get(contador).getNacionalidad());
        }
        else if ((piloto == 2) || (piloto == -2)){
                txt_nombre_conductor2.setText(lista.get(contador).getNombre_piloto());

               txt_apellido2.setText(lista.get(contador).getApellido());
                
                txt_nacionalidad_conductor2.setText(lista.get(contador).getNacionalidad());
        }
        
       }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reporte6_vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reporte6_vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reporte6_vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reporte6_vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reporte6_vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnanterior;
    private javax.swing.JButton btnsiguiente1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> combo_fabricante;
    private javax.swing.JComboBox<String> combo_modelo;
    private javax.swing.JLabel etiquetaTiempo;
    private javax.swing.JLabel etiquetaTiempo2;
    private javax.swing.JLabel etiquetaTiempo3;
    private javax.swing.JLabel etiquetaTiempo4;
    private javax.swing.JLabel etiquetaTiempo5;
    private javax.swing.JTextField fabricante_type;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nohay;
    private javax.swing.JLabel txt_apellido;
    private javax.swing.JLabel txt_apellido1;
    private javax.swing.JLabel txt_apellido2;
    private javax.swing.JLabel txt_categoria;
    private javax.swing.JLabel txt_fabricante;
    private javax.swing.JLabel txt_modelo;
    private javax.swing.JLabel txt_motor;
    private javax.swing.JLabel txt_nacionalidad_conductor;
    private javax.swing.JLabel txt_nacionalidad_conductor1;
    private javax.swing.JLabel txt_nacionalidad_conductor2;
    private javax.swing.JLabel txt_nombre_conductor;
    private javax.swing.JLabel txt_nombre_conductor1;
    private javax.swing.JLabel txt_nombre_conductor2;
    private javax.swing.JLabel txt_nombre_equipo;
    private javax.swing.JLabel txt_tipo;
    private javax.swing.JLabel txtnumero_equipo;
    // End of variables declaration//GEN-END:variables
}
