/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Clases.Carrera;
import Clases.Reporte1;
import Clases.Reporte4;

import conexion.Reporte1Conexion;
import conexion.ParticipanteConexion;
import conexion.ReportesConexion;
import control.control;
import javax.swing.table.TableColumnModel;


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Time;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RojeruSan
 */
public class Reporte4_vista extends javax.swing.JFrame {

    
    control con = new control();
    
    ArrayList<Reporte4> lista = new ArrayList<Reporte4>();
    
    ReportesConexion reporte_conexion = new ReportesConexion();
    
    
    int contador = 0;
    int id_donde_termina = 0;
    int id_anterior = 0;
    int numero_evento_viejo = 0;
   
    
  public Reporte4_vista() {
        initComponents();
        
        con.iniciaVentana(this);
       
        this.setLocationRelativeTo(this);
            this.setSize(1800,1800);
        btnsiguiente1.setVisible(false);
        btnanterior.setVisible(false);
         
        
        con.llenarComboAno(combo_ano);
        con.llenarComboEquipo(combo_equipo);
          
    }

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnCerrar = new javax.swing.JButton();
        etiquetaTiempo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_nacionalidad_equipo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_nombre_equipo = new javax.swing.JLabel();
        combo_equipo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtnumero_equipo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_puesto_carrera = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_nombre_conductor = new javax.swing.JLabel();
        txt_apellido = new javax.swing.JLabel();
        txt_nacionalidad_conductor = new javax.swing.JLabel();
        etiquetaTiempo2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_nombre_automovil = new javax.swing.JLabel();
        txt_motor = new javax.swing.JLabel();
        txt_categoria = new javax.swing.JLabel();
        nohay = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_nombre_conductor1 = new javax.swing.JLabel();
        txt_apellido1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txt_nacionalidad_conductor1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txt_nombre_conductor2 = new javax.swing.JLabel();
        txt_apellido2 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txt_nacionalidad_conductor2 = new javax.swing.JLabel();
        etiquetaTiempo3 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txt_numero_vuelta = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txt_km = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txt_mejor_vuelta = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txt_velocidad_media = new javax.swing.JLabel();
        etiquetaTiempo4 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txt_diferencia = new javax.swing.JLabel();
        btnanterior = new javax.swing.JButton();
        btnsiguiente1 = new javax.swing.JButton();
        combo_ano = new javax.swing.JComboBox<>();
        etiquetaTiempo5 = new javax.swing.JLabel();
        etiquetaTiempo6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCerrar.setBackground(new java.awt.Color(0, 153, 204));
        btnCerrar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setText("X");
        btnCerrar.setBorder(null);
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrar.setOpaque(true);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 30, 43, 45));

        etiquetaTiempo.setFont(new java.awt.Font("Lucida Sans", 0, 36)); // NOI18N
        etiquetaTiempo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaTiempo.setText("Datos del Automovil");
        jPanel1.add(etiquetaTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 180, 390, 90));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Nacionalidad:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 160, 40));

        txt_nacionalidad_equipo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txt_nacionalidad_equipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 380, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Nombre:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 120, 40));

        txt_nombre_equipo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txt_nombre_equipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 560, 40));

        combo_equipo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        combo_equipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_equipoActionPerformed(evt);
            }
        });
        jPanel1.add(combo_equipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 70, 210, 40));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 50, 120, 50));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Numero de Equipo:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 210, 40));

        txtnumero_equipo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txtnumero_equipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 180, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Posición:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 110, 40));

        txt_puesto_carrera.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txt_puesto_carrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 200, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("Nombres:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 640, 110, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("Apellidos:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 680, 120, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Nacionalidad:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 720, 160, 40));

        txt_nombre_conductor.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txt_nombre_conductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 640, 310, 40));

        txt_apellido.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txt_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 680, 330, 40));

        txt_nacionalidad_conductor.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txt_nacionalidad_conductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 720, 280, 40));

        etiquetaTiempo2.setFont(new java.awt.Font("Lucida Sans", 0, 36)); // NOI18N
        etiquetaTiempo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaTiempo2.setText("Datos de los Conductores");
        jPanel1.add(etiquetaTiempo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 540, 450, 90));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("Nombre:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 270, 110, 40));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setText("Motor:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 310, 90, 40));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setText("Categoría:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 350, 130, 40));

        txt_nombre_automovil.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txt_nombre_automovil, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 270, 450, 40));

        txt_motor.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txt_motor, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 310, 500, 40));

        txt_categoria.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txt_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 350, 390, 40));

        nohay.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nohay.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(nohay, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 380, 40));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel15.setText("Nombres:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 640, 110, 40));

        txt_nombre_conductor1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txt_nombre_conductor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 640, 290, 40));

        txt_apellido1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txt_apellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 680, 310, 40));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel16.setText("Apellidos:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 680, 120, 40));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel17.setText("Nacionalidad:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 720, 160, 40));

        txt_nacionalidad_conductor1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txt_nacionalidad_conductor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 720, 270, 40));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel18.setText("Nombres:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 640, 110, 40));

        txt_nombre_conductor2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txt_nombre_conductor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 640, 410, 40));

        txt_apellido2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txt_apellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 680, 400, 40));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel19.setText("Apellidos:");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 680, 120, 40));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel20.setText("Nacionalidad:");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 720, 160, 40));

        txt_nacionalidad_conductor2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txt_nacionalidad_conductor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 720, 280, 40));

        etiquetaTiempo3.setFont(new java.awt.Font("Lucida Sans", 0, 36)); // NOI18N
        etiquetaTiempo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaTiempo3.setText("Equipo");
        jPanel1.add(etiquetaTiempo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, -10, 320, 90));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel21.setText("Número de Vueltas:");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 220, 40));

        txt_numero_vuelta.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txt_numero_vuelta, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, 200, 40));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel22.setText("Kilómetros Recorridos:");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 250, 40));

        txt_km.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txt_km, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, 200, 40));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel23.setText("Tiempo de Mejor Vuelta:");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, 280, 40));

        txt_mejor_vuelta.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txt_mejor_vuelta, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 470, 200, 40));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel24.setText("Velocidad Media:");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 360, 190, 40));

        txt_velocidad_media.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txt_velocidad_media, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 360, 200, 40));

        etiquetaTiempo4.setFont(new java.awt.Font("Lucida Sans", 0, 36)); // NOI18N
        etiquetaTiempo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaTiempo4.setText("Datos de la Carrera");
        jPanel1.add(etiquetaTiempo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 400, 90));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel26.setText("Puesto:");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 100, 40));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel27.setText("Diferencia con el Equipo Anterior:");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 400, 370, 40));

        txt_diferencia.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txt_diferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 400, 260, 40));

        btnanterior.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnanterior.setText("Anterior");
        btnanterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnanteriorActionPerformed(evt);
            }
        });
        jPanel1.add(btnanterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 110, 170, 50));

        btnsiguiente1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnsiguiente1.setText("Siguiente");
        btnsiguiente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsiguiente1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnsiguiente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 110, 170, 50));

        combo_ano.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        combo_ano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_anoActionPerformed(evt);
            }
        });
        jPanel1.add(combo_ano, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 210, 40));

        etiquetaTiempo5.setFont(new java.awt.Font("Lucida Sans", 0, 36)); // NOI18N
        etiquetaTiempo5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaTiempo5.setText("Datos del Equipo");
        jPanel1.add(etiquetaTiempo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 320, 90));

        etiquetaTiempo6.setFont(new java.awt.Font("Lucida Sans", 0, 36)); // NOI18N
        etiquetaTiempo6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaTiempo6.setText("Año");
        jPanel1.add(etiquetaTiempo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, -10, 320, 90));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-130, 0, 1570, 910));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        Principal ventana = new  Principal();
                   con.activaVentana(ventana, this);  
                   
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try{
            nohay.setText("");
     
        
       String ano = combo_equipo.getSelectedItem().toString();
        
       int numero_equipo = Integer.parseInt(combo_equipo.getSelectedItem().toString());
        
        this.lista = reporte_conexion.reporte4(ano,numero_equipo);
        
        if(!this.lista.isEmpty()){
        subir();
        }else{
            nohay.setText("No hay Registros de esta Busqueda");
        }
        }catch(Exception e){
            nohay.setText("No hay Registros de esta Busqueda");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void combo_equipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_equipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_equipoActionPerformed

    private void btnanteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnanteriorActionPerformed
        this.contador --;
        btnsiguiente1.setVisible(true);
        try{
            anterior();
        }catch(Exception e){
            btnanterior.setVisible(false);
        }
    }//GEN-LAST:event_btnanteriorActionPerformed

    private void btnsiguiente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsiguiente1ActionPerformed
        this.contador ++;
        btnanterior.setVisible(true);
        try{
            siguiente();
            
        }catch(Exception e){
            btnsiguiente1.setVisible(false);
        }
    }//GEN-LAST:event_btnsiguiente1ActionPerformed

    private void combo_anoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_anoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_anoActionPerformed

    
    public void subir(){
        
        
       try{
        int marcador = this.id_donde_termina;
        int contador = 0;
        int i = 0;
        
       
                
                if(this.lista.get(0).getCantidad_pilotos() == 3){
                  mostrar(0,0);
                  mostrar(0+1,1);
                  mostrar(0+2,2);
                  this.id_donde_termina = 3;
                  }
                
                if(this.lista.size() > 3){
                     btnsiguiente1.setVisible(true);
                }
       }catch(Exception e){
           System.out.println("llego al final");
       }
       }
    
    public void siguiente(){
        
        try{
        
           
        int cantidad_pilotos = 0;
        int contador = 0;
        int i = this.id_donde_termina;
        int o=0;
       
        
       if(this.lista.size() != i){
              if(this.lista.get(i).getCantidad_pilotos() == 3){
                  this.id_anterior = i-1;
                  mostrar(i,0);
                  mostrar(i+1,1);
                  mostrar(i+2,2);
                  
                  i= i+3;
                  this.id_donde_termina = i;
              
            } 
              
       }
          
       if(this.lista.size() == i){
           btnsiguiente1.setVisible(false);
             System.out.println("llego al final en siguiente");
       }
       
       
        }catch(Exception e){
            
            //ocultamos el boton siguiente ya que llego al final
             btnsiguiente1.setVisible(false);
             System.out.println("error en siguiente");
         }
       
       }
    
    
    public void anterior(){
        
        try{
        
           
        int cantidad_pilotos = 0;
        int contador = 0;
        int i = this.id_anterior;
        int o=0;
       
           
            
       if(this.id_anterior != -1){
              if(this.lista.get(i).getCantidad_pilotos() == 3){
                  mostrar(i-2,0);
                  mostrar(i-1,1);
                  mostrar(i,2);
                  this.id_anterior = i - 3;
                 
                  this.id_donde_termina = i+1;
              
            } 
              
       }
       
       if(this.id_anterior == -1){
           btnanterior.setVisible(false);
             System.out.println("llego al final en anterior");
       }
       
       
        }catch(Exception e){
            
            //ocultamos el boton siguiente ya que llego al final
             btnanterior.setVisible(false);
             System.out.println("error en anterior");
         }
       
       }
    
    
    
    
    
 
    
    
    public void mostrar(int contador,int piloto){
       // System.out.println("imprimir   contador "+contador+"   piloto  "+piloto );
        if(piloto == 0){
        txt_nombre_equipo.setText(lista.get(contador).getNombre_equipo());
        txtnumero_equipo.setText(Integer.toString(lista.get(contador).getNumero_equipo()));
       // txt_nacionalidad_equipo.setText(lista.get(contador).getNacionalidad_equipo());
        
        txt_puesto_carrera.setText(Integer.toString(lista.get(contador).getPosicioncarrera()));
        txt_numero_vuelta.setText(Integer.toString(lista.get(contador).getVueltascarrera()));
        txt_km.setText(Double.toString(lista.get(contador).getKmcarrera()));
        txt_mejor_vuelta.setText(lista.get(contador).getVuelta_rapida_carrera());
        txt_velocidad_media.setText(Double.toString(lista.get(contador).getVelocidad_media()));
        
        DecimalFormat df = new DecimalFormat("#0.00");
             
        txt_diferencia.setText(df.format(lista.get(contador).getDiferencia()));
       
        txt_nombre_automovil.setText(lista.get(contador).getFabricante()+" "+lista.get(contador).getModelo());
        txt_motor.setText(lista.get(contador).getCaracteristicas_vehiculo());
        txt_categoria.setText(lista.get(contador).getCategoria_vehiculo());
        
        
        if(lista.get(contador).getNombre2() != null)
        txt_nombre_conductor.setText(lista.get(contador).getNombre_piloto()+" "+lista.get(contador).getNombre2());
        else
             txt_nombre_conductor.setText(lista.get(contador).getNombre_piloto());
        
        if(lista.get(contador).getApellido() != null)
        txt_apellido.setText(lista.get(contador).getApellido()+" "+lista.get(contador).getApellido2());
        else
        txt_apellido.setText(lista.get(contador).getApellido());
        
        
        txt_nacionalidad_conductor.setText(lista.get(contador).getNacionalidad());
        } else if ((piloto == 1) || (piloto == -1)){
             
                if(lista.get(contador).getNombre2() != null)
                txt_nombre_conductor1.setText(lista.get(contador).getNombre_piloto()+" "+lista.get(contador).getNombre2());
                else
                     txt_nombre_conductor1.setText(lista.get(contador).getNombre_piloto());

                if(lista.get(contador).getApellido() != null)
                txt_apellido1.setText(lista.get(contador).getApellido()+" "+lista.get(contador).getApellido2());
                else
                txt_apellido1.setText(lista.get(contador).getApellido());
                
                txt_nacionalidad_conductor1.setText(lista.get(contador).getNacionalidad());
        }
        else if ((piloto == 2) || (piloto == -2)){
             if(lista.get(contador).getNombre2() != null)
                txt_nombre_conductor2.setText(lista.get(contador).getNombre_piloto()+" "+lista.get(contador).getNombre2());
                else
                     txt_nombre_conductor2.setText(lista.get(contador).getNombre_piloto());

                if(lista.get(contador).getApellido() != null)
                txt_apellido2.setText(lista.get(contador).getApellido()+" "+lista.get(contador).getApellido2());
                else
                txt_apellido2.setText(lista.get(contador).getApellido());
                
                txt_nacionalidad_conductor2.setText(lista.get(contador).getNacionalidad());
        }
        
       }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reporte4_vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reporte4_vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reporte4_vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reporte4_vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reporte4_vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnanterior;
    private javax.swing.JButton btnsiguiente1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> combo_ano;
    private javax.swing.JComboBox<String> combo_equipo;
    private javax.swing.JLabel etiquetaTiempo;
    private javax.swing.JLabel etiquetaTiempo2;
    private javax.swing.JLabel etiquetaTiempo3;
    private javax.swing.JLabel etiquetaTiempo4;
    private javax.swing.JLabel etiquetaTiempo5;
    private javax.swing.JLabel etiquetaTiempo6;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nohay;
    private javax.swing.JLabel txt_apellido;
    private javax.swing.JLabel txt_apellido1;
    private javax.swing.JLabel txt_apellido2;
    private javax.swing.JLabel txt_categoria;
    private javax.swing.JLabel txt_diferencia;
    private javax.swing.JLabel txt_km;
    private javax.swing.JLabel txt_mejor_vuelta;
    private javax.swing.JLabel txt_motor;
    private javax.swing.JLabel txt_nacionalidad_conductor;
    private javax.swing.JLabel txt_nacionalidad_conductor1;
    private javax.swing.JLabel txt_nacionalidad_conductor2;
    private javax.swing.JLabel txt_nacionalidad_equipo;
    private javax.swing.JLabel txt_nombre_automovil;
    private javax.swing.JLabel txt_nombre_conductor;
    private javax.swing.JLabel txt_nombre_conductor1;
    private javax.swing.JLabel txt_nombre_conductor2;
    private javax.swing.JLabel txt_nombre_equipo;
    private javax.swing.JLabel txt_numero_vuelta;
    private javax.swing.JLabel txt_puesto_carrera;
    private javax.swing.JLabel txt_velocidad_media;
    private javax.swing.JLabel txtnumero_equipo;
    // End of variables declaration//GEN-END:variables
}
